### ISSUE TITLE
I could not build v4.4.5

### ISSUE THREAD

**Issue by raphaelcervantes** [driplineorg/dripline-python#115]
I am pasting the output of the docker build.
```
➜  dripline-python git:(33532c3) docker build . -t driplineorg/dripline-python:v4.4.5-amd64
Sending build context to Docker daemon  2.851MB
Step 1/18 : ARG img_user=amd64
Step 2/18 : ARG img_repo=python
Step 3/18 : ARG img_tag=3.7
Step 4/18 : from ${img_user}/${img_repo}:${img_tag}
 ---> 859d8ec7db6a
Step 5/18 : RUN apt-get update && apt-get install -y         cmake         build-essential         gdb         libboost-all-dev         librabbitmq-dev         wget &&    rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 297e182d1f58
Step 6/18 : COPY dripline-cpp /usr/local/src/dripline-cpp
 ---> Using cache
 ---> c2a74ca5e711
Step 7/18 : COPY module_bindings /usr/local/src/module_bindings
 ---> Using cache
 ---> a9d408997e1f
Step 8/18 : COPY dripline /usr/local/src/dripline
 ---> Using cache
 ---> 247ed40e8d21
Step 9/18 : COPY bin /usr/local/src/bin
 ---> Using cache
 ---> 0dfc5fe7007b
Step 10/18 : COPY .git /usr/local/src/.git
 ---> Using cache
 ---> 899c5677f6bd
Step 11/18 : COPY setup.py /usr/local/src/setup.py
 ---> Using cache
 ---> 822e54711765
Step 12/18 : COPY CMakeLists.txt /usr/local/src/CMakeLists.txt
 ---> Using cache
 ---> 2ef25465dcfb
Step 13/18 : COPY tests /usr/local/src/tests
 ---> Using cache
 ---> 80a7b3670bdf
Step 14/18 : ENV LD_LIBRARY_PATH /usr/local/lib
 ---> Using cache
 ---> 001e344d6fd2
Step 15/18 : RUN pip install ipython
 ---> Using cache
 ---> 2fb77e724912
Step 16/18 : RUN pip install pytest
 ---> Using cache
 ---> acf2b86f121b
Step 17/18 : RUN pip install /usr/local/src
 ---> Running in 3584d616b3bb
Processing /usr/local/src
Collecting PyYAML
  Downloading PyYAML-5.3.1.tar.gz (269 kB)
Collecting asteval
  Downloading asteval-0.9.18.tar.gz (52 kB)
Collecting setuptools_scm
  Downloading setuptools_scm-4.1.2-py2.py3-none-any.whl (27 kB)
Collecting sqlalchemy
  Downloading SQLAlchemy-1.3.18-cp37-cp37m-manylinux2010_x86_64.whl (1.3 MB)
Collecting psycopg2
  Downloading psycopg2-2.8.5.tar.gz (380 kB)
Collecting colorlog
  Downloading colorlog-4.1.0-py2.py3-none-any.whl (14 kB)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/site-packages (from setuptools_scm->dripline==0.0.0) (46.1.3)
Building wheels for collected packages: dripline, PyYAML, asteval, psycopg2
  Building wheel for dripline (setup.py): started
  Building wheel for dripline (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-256w98tu/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-256w98tu/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-9h3crcxr
       cwd: /tmp/pip-req-build-256w98tu/
  Complete output (89 lines):
  packages are: ['dripline', 'dripline.core', 'dripline.extensions', 'dripline.implementations']
  /usr/local/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'use_scm_version'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/dripline
  copying dripline/__init__.py -> build/lib.linux-x86_64-3.7/dripline
  creating build/lib.linux-x86_64-3.7/dripline/core
  copying dripline/core/endpoint.py -> build/lib.linux-x86_64-3.7/dripline/core
  copying dripline/core/calibrate.py -> build/lib.linux-x86_64-3.7/dripline/core
  copying dripline/core/return_codes.py -> build/lib.linux-x86_64-3.7/dripline/core
  copying dripline/core/interface.py -> build/lib.linux-x86_64-3.7/dripline/core
  copying dripline/core/entity.py -> build/lib.linux-x86_64-3.7/dripline/core
  copying dripline/core/throw_reply.py -> build/lib.linux-x86_64-3.7/dripline/core
  copying dripline/core/alert_consumer.py -> build/lib.linux-x86_64-3.7/dripline/core
  copying dripline/core/__init__.py -> build/lib.linux-x86_64-3.7/dripline/core
  creating build/lib.linux-x86_64-3.7/dripline/extensions
  copying dripline/extensions/__init__.py -> build/lib.linux-x86_64-3.7/dripline/extensions
  creating build/lib.linux-x86_64-3.7/dripline/implementations
  copying dripline/implementations/key_value_store.py -> build/lib.linux-x86_64-3.7/dripline/implementations
  copying dripline/implementations/postgres_sensor_logger.py -> build/lib.linux-x86_64-3.7/dripline/implementations
  copying dripline/implementations/ethernet_scpi_service.py -> build/lib.linux-x86_64-3.7/dripline/implementations
  copying dripline/implementations/entity_endpoints.py -> build/lib.linux-x86_64-3.7/dripline/implementations
  copying dripline/implementations/postgres_interface.py -> build/lib.linux-x86_64-3.7/dripline/implementations
  copying dripline/implementations/__init__.py -> build/lib.linux-x86_64-3.7/dripline/implementations
  running build_ext
  remove cache
  should make a cmake call:
  cmake /tmp/pip-req-build-256w98tu -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-req-build-256w98tu/build/lib.linux-x86_64-3.7 -DPYTHON_EXECUTABLE=/usr/local/bin/python -DCMAKE_INSTALL_PREFIX:PATH=/usr/local -DDripline_BUILD_EXAMPLES:bool=1 -DScarab_PYBIND:bool=1 -DCMAKE_BUILD_TYPE=Release cwd=build/temp.linux-x86_64-3.7 env={'HOSTNAME': '3584d616b3bb', 'PYTHON_PIP_VERSION': '20.0.2', 'LD_LIBRARY_PATH': '/usr/local/lib', 'HOME': '/root', 'GPG_KEY': '0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D', 'PYTHON_GET_PIP_URL': 'https://github.com/pypa/get-pip/raw/d59197a3c169cef378a22428a3fa99d33e080a5d/get-pip.py', 'PATH': '/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'LANG': 'C.UTF-8', 'PYTHON_VERSION': '3.7.7', 'PWD': '/', 'PYTHON_GET_PIP_SHA256': '421ac1d44c0cf9730a088e337867d974b91bdce4ea2636099275071878cc189e', 'PLAT': 'linux-x86_64', 'PIP_REQ_TRACKER': '/tmp/pip-req-tracker-ewaq7nna', 'CXXFLAGS': ' -DVERSION_INFO=\\"0.0.0\\"'}
  -- The C compiler identification is GNU 8.3.0
  -- The CXX compiler identification is GNU 8.3.0
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  CMake Error at CMakeLists.txt:5 (include):
    include could not find load file:
  
      PackageBuilder
  
  
  CMake Error at CMakeLists.txt:7 (pbuilder_prepare_project):
    Unknown CMake command "pbuilder_prepare_project".
  
  
  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-req-build-256w98tu/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeOutput.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-256w98tu/setup.py", line 106, in <module>
      scripts=["bin/dl-serve"]
    File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-256w98tu/setup.py", line 32, in run
      self.build_extension(ext)
    File "/tmp/pip-req-build-256w98tu/setup.py", line 66, in build_extension
      subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
    File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-req-build-256w98tu', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-req-build-256w98tu/build/lib.linux-x86_64-3.7', '-DPYTHON_EXECUTABLE=/usr/local/bin/python', '-DCMAKE_INSTALL_PREFIX:PATH=/usr/local', '-DDripline_BUILD_EXAMPLES:bool=1', '-DScarab_PYBIND:bool=1', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for dripline
  Running setup.py clean for dripline
  Building wheel for PyYAML (setup.py): started
  Building wheel for PyYAML (setup.py): finished with status 'done'
  Created wheel for PyYAML: filename=PyYAML-5.3.1-cp37-cp37m-linux_x86_64.whl size=471257 sha256=29ac863343ae75a92ceb671acd90eda3619811bb8ad6cccc4c279d017401cb33
  Stored in directory: /root/.cache/pip/wheels/5e/03/1e/e1e954795d6f35dfc7b637fe2277bff021303bd9570ecea653
  Building wheel for asteval (setup.py): started
  Building wheel for asteval (setup.py): finished with status 'done'
  Created wheel for asteval: filename=asteval-0.9.18-py3-none-any.whl size=17382 sha256=dd430f537a931e1d5123570de38d32a4b0de0070adf8090a18d7d000a473b29f
  Stored in directory: /root/.cache/pip/wheels/43/b8/44/8f2a3365bf885f53af98f1528cf7dbc2a8bc81916f678bc045
  Building wheel for psycopg2 (setup.py): started
  Building wheel for psycopg2 (setup.py): finished with status 'done'
  Created wheel for psycopg2: filename=psycopg2-2.8.5-cp37-cp37m-linux_x86_64.whl size=467610 sha256=70ce8786700a20aaa3816417116a9fadbbf5cc03b7e2b2884ae73c580b14a52f
  Stored in directory: /root/.cache/pip/wheels/69/74/ec/7764aea035627654bf137f89a91405ac239c569ce10ae87137
Successfully built PyYAML asteval psycopg2
Failed to build dripline
Installing collected packages: PyYAML, asteval, setuptools-scm, sqlalchemy, psycopg2, colorlog, dripline
    Running setup.py install for dripline: started
    Running setup.py install for dripline: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-256w98tu/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-256w98tu/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-fh523x4y/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7m/dripline
         cwd: /tmp/pip-req-build-256w98tu/
    Complete output (92 lines):
    packages are: ['dripline', 'dripline.core', 'dripline.extensions', 'dripline.implementations']
    /usr/local/lib/python3.7/site-packages/setuptools/dist.py:454: UserWarning: Normalizing 'v4.4.5' to '4.4.5'
      warnings.warn(tmpl.format(**locals()))
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/dripline
    copying dripline/__init__.py -> build/lib.linux-x86_64-3.7/dripline
    copying dripline/version.py -> build/lib.linux-x86_64-3.7/dripline
    creating build/lib.linux-x86_64-3.7/dripline/core
    copying dripline/core/endpoint.py -> build/lib.linux-x86_64-3.7/dripline/core
    copying dripline/core/calibrate.py -> build/lib.linux-x86_64-3.7/dripline/core
    copying dripline/core/return_codes.py -> build/lib.linux-x86_64-3.7/dripline/core
    copying dripline/core/interface.py -> build/lib.linux-x86_64-3.7/dripline/core
    copying dripline/core/entity.py -> build/lib.linux-x86_64-3.7/dripline/core
    copying dripline/core/throw_reply.py -> build/lib.linux-x86_64-3.7/dripline/core
    copying dripline/core/alert_consumer.py -> build/lib.linux-x86_64-3.7/dripline/core
    copying dripline/core/__init__.py -> build/lib.linux-x86_64-3.7/dripline/core
    creating build/lib.linux-x86_64-3.7/dripline/extensions
    copying dripline/extensions/__init__.py -> build/lib.linux-x86_64-3.7/dripline/extensions
    creating build/lib.linux-x86_64-3.7/dripline/implementations
    copying dripline/implementations/key_value_store.py -> build/lib.linux-x86_64-3.7/dripline/implementations
    copying dripline/implementations/postgres_sensor_logger.py -> build/lib.linux-x86_64-3.7/dripline/implementations
    copying dripline/implementations/ethernet_scpi_service.py -> build/lib.linux-x86_64-3.7/dripline/implementations
    copying dripline/implementations/entity_endpoints.py -> build/lib.linux-x86_64-3.7/dripline/implementations
    copying dripline/implementations/postgres_interface.py -> build/lib.linux-x86_64-3.7/dripline/implementations
    copying dripline/implementations/__init__.py -> build/lib.linux-x86_64-3.7/dripline/implementations
    running build_ext
    remove cache
    should make a cmake call:
    cmake /tmp/pip-req-build-256w98tu -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-req-build-256w98tu/build/lib.linux-x86_64-3.7 -DPYTHON_EXECUTABLE=/usr/local/bin/python -DCMAKE_INSTALL_PREFIX:PATH=/usr/local -DDripline_BUILD_EXAMPLES:bool=1 -DScarab_PYBIND:bool=1 -DCMAKE_BUILD_TYPE=Release cwd=build/temp.linux-x86_64-3.7 env={'HOSTNAME': '3584d616b3bb', 'PYTHON_PIP_VERSION': '20.0.2', 'LD_LIBRARY_PATH': '/usr/local/lib', 'HOME': '/root', 'GPG_KEY': '0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D', 'PYTHON_GET_PIP_URL': 'https://github.com/pypa/get-pip/raw/d59197a3c169cef378a22428a3fa99d33e080a5d/get-pip.py', 'PATH': '/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'LANG': 'C.UTF-8', 'PYTHON_VERSION': '3.7.7', 'PWD': '/', 'PYTHON_GET_PIP_SHA256': '421ac1d44c0cf9730a088e337867d974b91bdce4ea2636099275071878cc189e', 'PLAT': 'linux-x86_64', 'PIP_REQ_TRACKER': '/tmp/pip-req-tracker-ewaq7nna', 'CXXFLAGS': ' -DVERSION_INFO=\\"4.4.5\\"'}
    -- The C compiler identification is GNU 8.3.0
    -- The CXX compiler identification is GNU 8.3.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    CMake Error at CMakeLists.txt:5 (include):
      include could not find load file:
    
        PackageBuilder
    
    
    CMake Error at CMakeLists.txt:7 (pbuilder_prepare_project):
      Unknown CMake command "pbuilder_prepare_project".
    
    
    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-req-build-256w98tu/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-256w98tu/setup.py", line 106, in <module>
        scripts=["bin/dl-serve"]
      File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-req-build-256w98tu/setup.py", line 32, in run
        self.build_extension(ext)
      File "/tmp/pip-req-build-256w98tu/setup.py", line 66, in build_extension
        subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
      File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-req-build-256w98tu', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-req-build-256w98tu/build/lib.linux-x86_64-3.7', '-DPYTHON_EXECUTABLE=/usr/local/bin/python', '-DCMAKE_INSTALL_PREFIX:PATH=/usr/local', '-DDripline_BUILD_EXAMPLES:bool=1', '-DScarab_PYBIND:bool=1', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-256w98tu/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-256w98tu/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-fh523x4y/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7m/dripline Check the logs for full command output.
WARNING: You are using pip version 20.0.2; however, version 20.1.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
The command '/bin/sh -c pip install /usr/local/src' returned a non-zero code: 1
```

**Comment by nsoblath** [comment]
Local build issue
