### ISSUE TITLE
seemingly benign error when I run dl-serve command

### ISSUE THREAD

**Issue by raphaelcervantes** [driplineorg/dripline-python#98]
I was running `dl-serve /root/key-value-store.yaml` on the first mesh kv-store example. Among other output, I get the error pasted below. I don't know what this error means and everything else seems to work as expected. I figured I would log this error in case it's of any importance. This is running dripline-python:v4.1.0.

```
got an error... need to implement handling
traceback was:
Traceback (most recent call last):
  File "/usr/local/bin/dl-serve", line 55, in run
    self._run(the_app)
  File "/usr/local/bin/dl-serve", line 68, in _run
    the_endpoints = run_config.pop("endpoints", [])
AttributeError: 'NoneType' object has no attribute 'pop'
```

Below is the full output.

```
root@106b41df4708:/# dl-serve /root/key-value-store.yaml
2020-05-12 21:11:28 [DEBUG] (tid 140333428037440) dexed_factory.hh(208): Registered a indexed_factory for class json at 0x7fa1eb646000, indexed_factory #0 for 0x55ee2c275670
2020-05-12 21:11:28 [DEBUG] (tid 140333428037440) dexed_factory.hh(208): Registered a indexed_factory for class json at 0x7fa1eb646040, indexed_factory #0 for 0x55ee2c2758b0
2020-05-12 21:11:28 [DEBUG] (tid 140333428037440) dexed_factory.hh(208): Registered a indexed_factory for class yaml at 0x7fa1eb646100, indexed_factory #1 for 0x55ee2c275670
2020-05-12 21:11:28 [DEBUG] (tid 140333428037440) dexed_factory.hh(208): Registered a indexed_factory for class yaml at 0x7fa1eb646140, indexed_factory #1 for 0x55ee2c2758b0
2020-05-12 21:11:28 [DEBUG] (tid 140333428037440) dexed_factory.hh(208): Registered a indexed_factory for class 0 at 0x7fa1eaf23830, indexed_factory #0 for 0x55ee2c2a66d0
2020-05-12 21:11:28 [DEBUG] (tid 140333428037440) dexed_factory.hh(208): Registered a indexed_factory for class 1 at 0x7fa1eaf23840, indexed_factory #1 for 0x55ee2c2a66d0
2020-05-12 21:11:28 [DEBUG] (tid 140333428037440) dexed_factory.hh(208): Registered a indexed_factory for class 100 at 0x7fa1eaf23850, indexed_factory #2 for 0x55ee2c2a66d0
2020-05-12 21:11:28 [DEBUG] (tid 140333428037440) dexed_factory.hh(208): Registered a indexed_factory for class 101 at 0x7fa1eaf23860, indexed_factory #3 for 0x55ee2c2a66d0
2020-05-12 21:11:28 [DEBUG] (tid 140333428037440) dexed_factory.hh(208): Registered a indexed_factory for class 102 at 0x7fa1eaf23870, indexed_factory #4 for 0x55ee2c2a66d0
2020-05-12 21:11:28 [DEBUG] (tid 140333428037440) dexed_factory.hh(208): Registered a indexed_factory for class 200 at 0x7fa1eaf23880, indexed_factory #5 for 0x55ee2c2a66d0
2020-05-12 21:11:28 [DEBUG] (tid 140333428037440) dexed_factory.hh(208): Registered a indexed_factory for class 201 at 0x7fa1eaf23890, indexed_factory #6 for 0x55ee2c2a66d0
2020-05-12 21:11:28 [DEBUG] (tid 140333428037440) dexed_factory.hh(208): Registered a indexed_factory for class 202 at 0x7fa1eaf238a0, indexed_factory #7 for 0x55ee2c2a66d0
2020-05-12 21:11:28 [DEBUG] (tid 140333428037440) dexed_factory.hh(208): Registered a indexed_factory for class 300 at 0x7fa1eaf238b0, indexed_factory #8 for 0x55ee2c2a66d0
2020-05-12 21:11:28 [DEBUG] (tid 140333428037440) dexed_factory.hh(208): Registered a indexed_factory for class 301 at 0x7fa1eaf238c0, indexed_factory #9 for 0x55ee2c2a66d0
2020-05-12 21:11:28 [DEBUG] (tid 140333428037440) dexed_factory.hh(208): Registered a indexed_factory for class 302 at 0x7fa1eaf238d0, indexed_factory #10 for 0x55ee2c2a66d0
2020-05-12 21:11:28 [DEBUG] (tid 140333428037440) dexed_factory.hh(208): Registered a indexed_factory for class 303 at 0x7fa1eaf238e0, indexed_factory #11 for 0x55ee2c2a66d0
2020-05-12 21:11:28 [DEBUG] (tid 140333428037440) dexed_factory.hh(208): Registered a indexed_factory for class 304 at 0x7fa1eaf238f0, indexed_factory #12 for 0x55ee2c2a66d0
2020-05-12 21:11:28 [DEBUG] (tid 140333428037440) dexed_factory.hh(208): Registered a indexed_factory for class 305 at 0x7fa1eaf23900, indexed_factory #13 for 0x55ee2c2a66d0
2020-05-12 21:11:28 [DEBUG] (tid 140333428037440) dexed_factory.hh(208): Registered a indexed_factory for class 306 at 0x7fa1eaf23910, indexed_factory #14 for 0x55ee2c2a66d0
2020-05-12 21:11:28 [DEBUG] (tid 140333428037440) dexed_factory.hh(208): Registered a indexed_factory for class 307 at 0x7fa1eaf23920, indexed_factory #15 for 0x55ee2c2a66d0
2020-05-12 21:11:28 [DEBUG] (tid 140333428037440) dexed_factory.hh(208): Registered a indexed_factory for class 308 at 0x7fa1eaf23930, indexed_factory #16 for 0x55ee2c2a66d0
2020-05-12 21:11:28 [DEBUG] (tid 140333428037440) dexed_factory.hh(208): Registered a indexed_factory for class 309 at 0x7fa1eaf23940, indexed_factory #17 for 0x55ee2c2a66d0
2020-05-12 21:11:28 [DEBUG] (tid 140333428037440) dexed_factory.hh(208): Registered a indexed_factory for class 310 at 0x7fa1eaf23950, indexed_factory #18 for 0x55ee2c2a66d0
2020-05-12 21:11:28 [DEBUG] (tid 140333428037440) dexed_factory.hh(208): Registered a indexed_factory for class 400 at 0x7fa1eaf23960, indexed_factory #19 for 0x55ee2c2a66d0
2020-05-12 21:11:28 [DEBUG] (tid 140333428037440) dexed_factory.hh(208): Registered a indexed_factory for class 401 at 0x7fa1eaf23970, indexed_factory #20 for 0x55ee2c2a66d0
2020-05-12 21:11:28 [DEBUG] (tid 140333428037440) dexed_factory.hh(208): Registered a indexed_factory for class 402 at 0x7fa1eaf23980, indexed_factory #21 for 0x55ee2c2a66d0
2020-05-12 21:11:28 [DEBUG] (tid 140333428037440) dexed_factory.hh(208): Registered a indexed_factory for class 403 at 0x7fa1eaf23990, indexed_factory #22 for 0x55ee2c2a66d0
2020-05-12 21:11:28 [DEBUG] (tid 140333428037440) dexed_factory.hh(208): Registered a indexed_factory for class 404 at 0x7fa1eaf239a0, indexed_factory #23 for 0x55ee2c2a66d0
2020-05-12 21:11:28 [DEBUG] (tid 140333428037440) dexed_factory.hh(208): Registered a indexed_factory for class 999 at 0x7fa1eaf239b0, indexed_factory #24 for 0x55ee2c2a66d0
version should be: 0.0.0
2020-05-12 21:11:29 [DEBUG] (tid 140333428037440) i/application.cc(109): first configuration stage
2020-05-12 21:11:29 [DEBUG] (tid 140333428037440) i/application.cc(117): second configuration stage
2020-05-12 21:11:29 [DEBUG] (tid 140333428037440) i/application.cc(140): third configuration stage
2020-05-12 21:11:29 [ PROG] (tid 140333428037440) i/application.cc(102): Final configuration:

{
    dripline :
    {
        alerts-exchange : alerts
        heartbeat-interval-s : 60
        heartbeat-routing-key : heartbeat
        loop-timeout-ms : 1000
        max-payload-size : 10000
        message-wait-ms : 1000
        requests-exchange : requests
    }

}

2020-05-12 21:11:29 [ PROG] (tid 140333428037440) i/application.cc(103): Ordered args:

[
    /root/key-value-store.yaml
]

python got a master config:

{
    dripline :
    {
        alerts-exchange : alerts
        heartbeat-interval-s : 60
        heartbeat-routing-key : heartbeat
        loop-timeout-ms : 1000
        max-payload-size : 10000
        message-wait-ms : 1000
        requests-exchange : requests
    }

}

got an error... need to implement handling
traceback was:
Traceback (most recent call last):
  File "/usr/local/bin/dl-serve", line 55, in run
    self._run(the_app)
  File "/usr/local/bin/dl-serve", line 68, in _run
    the_endpoints = run_config.pop("endpoints", [])
AttributeError: 'NoneType' object has no attribute 'pop'

2020-05-12 21:11:29 [DEBUG] (tid 140333428037440) dexed_factory.hh(220): Removing indexed_factory for class 999 from 0x55ee2c2a66d0
2020-05-12 21:11:29 [DEBUG] (tid 140333428037440) dexed_factory.hh(220): Removing indexed_factory for class 404 from 0x55ee2c2a66d0
2020-05-12 21:11:29 [DEBUG] (tid 140333428037440) dexed_factory.hh(220): Removing indexed_factory for class 403 from 0x55ee2c2a66d0
2020-05-12 21:11:29 [DEBUG] (tid 140333428037440) dexed_factory.hh(220): Removing indexed_factory for class 402 from 0x55ee2c2a66d0
2020-05-12 21:11:29 [DEBUG] (tid 140333428037440) dexed_factory.hh(220): Removing indexed_factory for class 401 from 0x55ee2c2a66d0
2020-05-12 21:11:29 [DEBUG] (tid 140333428037440) dexed_factory.hh(220): Removing indexed_factory for class 400 from 0x55ee2c2a66d0
2020-05-12 21:11:29 [DEBUG] (tid 140333428037440) dexed_factory.hh(220): Removing indexed_factory for class 310 from 0x55ee2c2a66d0
2020-05-12 21:11:29 [DEBUG] (tid 140333428037440) dexed_factory.hh(220): Removing indexed_factory for class 309 from 0x55ee2c2a66d0
2020-05-12 21:11:29 [DEBUG] (tid 140333428037440) dexed_factory.hh(220): Removing indexed_factory for class 308 from 0x55ee2c2a66d0
2020-05-12 21:11:29 [DEBUG] (tid 140333428037440) dexed_factory.hh(220): Removing indexed_factory for class 307 from 0x55ee2c2a66d0
2020-05-12 21:11:29 [DEBUG] (tid 140333428037440) dexed_factory.hh(220): Removing indexed_factory for class 306 from 0x55ee2c2a66d0
2020-05-12 21:11:29 [DEBUG] (tid 140333428037440) dexed_factory.hh(220): Removing indexed_factory for class 305 from 0x55ee2c2a66d0
2020-05-12 21:11:29 [DEBUG] (tid 140333428037440) dexed_factory.hh(220): Removing indexed_factory for class 304 from 0x55ee2c2a66d0
2020-05-12 21:11:29 [DEBUG] (tid 140333428037440) dexed_factory.hh(220): Removing indexed_factory for class 303 from 0x55ee2c2a66d0
2020-05-12 21:11:29 [DEBUG] (tid 140333428037440) dexed_factory.hh(220): Removing indexed_factory for class 302 from 0x55ee2c2a66d0
2020-05-12 21:11:29 [DEBUG] (tid 140333428037440) dexed_factory.hh(220): Removing indexed_factory for class 301 from 0x55ee2c2a66d0
2020-05-12 21:11:29 [DEBUG] (tid 140333428037440) dexed_factory.hh(220): Removing indexed_factory for class 300 from 0x55ee2c2a66d0
2020-05-12 21:11:29 [DEBUG] (tid 140333428037440) dexed_factory.hh(220): Removing indexed_factory for class 202 from 0x55ee2c2a66d0
2020-05-12 21:11:29 [DEBUG] (tid 140333428037440) dexed_factory.hh(220): Removing indexed_factory for class 201 from 0x55ee2c2a66d0
2020-05-12 21:11:29 [DEBUG] (tid 140333428037440) dexed_factory.hh(220): Removing indexed_factory for class 200 from 0x55ee2c2a66d0
2020-05-12 21:11:29 [DEBUG] (tid 140333428037440) dexed_factory.hh(220): Removing indexed_factory for class 102 from 0x55ee2c2a66d0
2020-05-12 21:11:29 [DEBUG] (tid 140333428037440) dexed_factory.hh(220): Removing indexed_factory for class 101 from 0x55ee2c2a66d0
2020-05-12 21:11:29 [DEBUG] (tid 140333428037440) dexed_factory.hh(220): Removing indexed_factory for class 100 from 0x55ee2c2a66d0
2020-05-12 21:11:29 [DEBUG] (tid 140333428037440) dexed_factory.hh(220): Removing indexed_factory for class 1 from 0x55ee2c2a66d0
2020-05-12 21:11:29 [DEBUG] (tid 140333428037440) dexed_factory.hh(220): Removing indexed_factory for class 0 from 0x55ee2c2a66d0
2020-05-12 21:11:29 [DEBUG] (tid 140333428037440) dexed_factory.hh(220): Removing indexed_factory for class yaml from 0x55ee2c2758b0
2020-05-12 21:11:29 [DEBUG] (tid 140333428037440) dexed_factory.hh(220): Removing indexed_factory for class yaml from 0x55ee2c275670
2020-05-12 21:11:29 [DEBUG] (tid 140333428037440) dexed_factory.hh(220): Removing indexed_factory for class json from 0x55ee2c2758b0
2020-05-12 21:11:29 [DEBUG] (tid 140333428037440) dexed_factory.hh(220): Removing indexed_factory for class json from 0x55ee2c275670
root@106b41df4708:/# exit
```

**Comment by laroque** [comment]
This error is because you didn't passed the config file path as just an arg in the ordered args list, it needs to be the argument to the `-c, --config` option. You could in principle pass the runtime config in another way, so that option is optional, but in practice you'll always need it. I suppose we could catch this and throw our own exception and message, though "run_config is None" is maybe pretty close to good enough.

**Comment by nsoblath** [comment]
The lack of `endpoints` now doesn't cause an error.  And the lack of a config file also will not cause an error.  I'm going to close this issue.
